spring:
  application:
    name: oct-nocode-backend
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.octaver.octnocode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn